<p>That should work. It looks like the exception is getting triggered in pingback/send_trackback and not send_pingback</p>
