<p>What you are seeing is that a NullPointerException has been thrown on the remote side, that exception was returned as a result, and re-thrown to your client.  In these situations it helps a lot for debugging to find out what the original exception is.  You can do this with a trick:</p>

<p>In your class that implements the interface, override onTransact() to do this:</p>

<pre><code>protected boolean onTransact(int code, Parcel data, Parcel reply, int flags) {
    try {
        super.onTransact(code, data, reply, flags);
    } catch (RuntimeException e) {
        Log.w("MyClass", "Unexpected remote exception", e);
        throw e;
    }
}
</code></pre>

<p>Now when the crash happens you will also see in the log the original exception printed, with the line where it happened.</p>
