<p>This is by design.  A first-chance exception notification doesn't mean that there's a problem.  The relevant code inside the Create() method looks like this:</p>

<pre><code>try
{
    metadata = source.Metadata as BitmapMetadata;
}
catch (NotSupportedException)
{
}
</code></pre>

<p>In other words, the exception is expected and simply swallowed.  Which is certainly very annoying since these exceptions <em>do</em> make the debugger stop when you have the Thrown checkbox checked in the Debug + Exception dialog.  But it certainly is not a bug, this was intentionally written this way.  Sometimes it is a lot cheaper to just let an exception be thrown and swallowing it instead of writing the code that prevents the exception.  Especially when it gets unpractical to avoid the exception, the case with bitmaps since there are so many different kind of bitmap types.  Some of which don't support metadata.  Wherever this is done inside the framework code, it is almost always done to make the code <em>faster</em>.  Speed is also an important aspect of code.</p>

<p>Feature, not a bug.  Untick the Thrown checkbox to avoid seeing these exceptions.</p>
