<p>You <b>MUST NOT</b> throw an exception out of a destructor.<br>
If an exception is already propagating then the application will terminate.<br></p>

<p>By terminate I mean stop immediately. Stack unwinding stops. No more destructors are called. All bad stuff. See the discussion here.</p>

<p><a href="http://stackoverflow.com/questions/130117/throwing-exceptions-out-of-a-destructor#130123">http://stackoverflow.com/questions/130117/throwing-exceptions-out-of-a-destructor#130123</a></p>

<p>I don't follow (as in disagree with) your logic that this causes the destructor to get more complicated.<br>
With the correct usage of smart pointers this actually makes the destructor simpler as everything now becomes automatic. Each class tides up its own little piece of the puzzle. No brain surgery or rocket science here. Another Big win for RAII.</p>

<p>As for the possibility of std::uncaught_exception() I point you at <a href="http://www.gotw.ca/gotw/047.htm">Herb Sutters article about why it does not work</a></p>
