<p>I got solution for this problem which has ultimately gave me as well as my client huge relief.</p>

<p><strong>And here is the reason and solution.</strong></p>

<p>The functions âsa_GetBlueâ and "sa_GetRed" was returning âPy_Falseâ.  Before returning âPy_Falseâ or âPy_Trueâ you need to increase the reference count of the variable holding these values otherwise It may corrupt memory state of the interpreter; it would not crash immediately but may crash at any point of time. In my case, It was crashing after processing 20000 to 50000 requests.</p>

<p>Please check below link to get more idea about what I am trying to explain.</p>

<p><a href="http://stackoverflow.com/questions/1460454/why-does-python-keep-a-reference-count-on-false-and-true">why-does-python-keep-a-reference-count-on-false-and-true</a></p>

<p>@doomster and @Omnifarious; Thank you for your comment and direction that you have provided.</p>
