<p>Well, you don't actually clarify about your exact failure, but I'd suspect an asynchronous operation (background thread) had been pulled into execution as soon </p>

<pre><code>Sleep(100);
</code></pre>

<p>was called, and caused an exception. If you don't have debuggable <code>[External Code]</code> the least point of capture will be your own code.</p>
