<p><em>You can either return value of throw Exception from a method, both can not be done at once.</em></p>

<p>You can create custom Exception class and where you can keep your processed result and throw that if exception arise. </p>

<pre><code>public class MyException extends Exception{
     private int[] processedResult;
     public MyException(String str,int[] result){
        this.processedResult = result;
     }
     ...
     @override
     public String toString(){
       ....
     }
} 
</code></pre>

<p>...</p>

<pre><code>public int [] pickNumbers(int n, int k) throws MyException{
    int[] larray = new int[n];
    try{
       ...
    }catch(Exception ex){
        new MyException("...",larray );
    }
}
</code></pre>
