<p>Well, I presume that error.to_dict() returns a dict, which wouldn't have a status code attribute (it's just a regular old dict). You might try this instead:</p>

<pre><code>@app.errorhandler(InvalidUsage)
def handle_invalid_usage(error):
    response = error.to_dict()
    response["status_code"] = error.status_code
    return response
</code></pre>

<p>That said, it seems odd that the dictionary wouldn't already have the error code in it. Maybe a bit more detail on what what you are trying to accomplish would help? If you don't call the second-to-last line, and just return response, what do you see?</p>
